import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#00205f",
        "on-primary": "#ffffff",
        "primary-container": "#00338d",
        "on-primary-container": "#81a1ff",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary-fixed": "#00174b",
        "on-primary-fixed-variant": "#19409a",
        "inverse-primary": "#b4c5ff",
        "secondary": "#006a68",
        "on-secondary": "#ffffff",
        "secondary-container": "#79f2f0",
        "on-secondary-container": "#006e6d",
        "secondary-fixed": "#7df5f3",
        "secondary-fixed-dim": "#5dd9d6",
        "on-secondary-fixed": "#00201f",
        "on-secondary-fixed-variant": "#00504f",
        "tertiary": "#172537",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#2d3b4e",
        "on-tertiary-container": "#97a5bc",
        "tertiary-fixed": "#d5e3fc",
        "tertiary-fixed-dim": "#b9c7df",
        "on-tertiary-fixed": "#0e1c2e",
        "on-tertiary-fixed-variant": "#3a485b",
        "error": "#BA1A1A",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "surface": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "surface-bright": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#ECEEF0",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "surface-variant": "#e0e3e5",
        "surface-tint": "#3759b3",
        "on-surface": "#191c1e",
        "on-surface-variant": "#444652",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "background": "#f7f9fb",
        "on-background": "#191c1e",
        "outline": "#747683",
        "outline-variant": "#c4c6d4",
        "pulse-teal-vibrant": "#00E1DE",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-desktop": "32px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "stack-lg": "32px",
        "stack-md": "16px",
        "stack-sm": "8px",
        "base": "8px",
        "sidebar-width": "280px",
      },
      fontFamily: {
        sans: ["IBM Plex Sans", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-lg":  ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "body-lg":  ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md":  ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm":  ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
